########### 数据源 ##########
spring:
  datasource:
    schema: classpath:sql/db.sql #启动执行的sql
    url: jdbc:mysql://localhost:3306/test_db2?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=false
    username: root
    password:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select now()
      initial-size: 10
      max-idle: 5
      test-while-idle: false
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 3600000
############ myBatis ##########
mybatis:
  mapperLocations: classpath:mapper/**/*.xml # xml映射文件路径
  configLocation: classpath:mybatis.xml      # mybatis总配置文件路径
  type-aliases-package: com.zm.entity # 类型别名包扫描路径
  configuration:
    map-underscore-to-camel-case: true # 启用驼峰命名